{% set name = "tike" %}
{% set version = "0.25.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/AdvancedPhotonSource/tike/releases/download/v{{ version }}/tike-v{{ version }}.zip
  sha256: fecce2fc9a4748ff33cedb32ae2c7fecbfc702651ad8c0cab907df74dcd3fff1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  # SCM doesn't handle v-prefix version information
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=61
    - setuptools_scm >=7
    - toml
    - wheel
  run:
    - cupy >=10.0,!=10.3.0,!=13.0.*
    - importlib_resources # backport for python<3.9
    - matplotlib-base ==3.*
    - numpy >=1.17,<2.dev0
    - python >=3.8
    - py-opencv >=3.4,<5
    - scipy >=1.6,<2.dev0
  run_constrained:
    - mpi4py =3.*

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - tike
    - tike.align
    - tike.communicators
    - tike.lamino
    - tike.ptycho
    - tike.linalg
    - tike.opt
    - tike.random
    - tike.scan
    - tike.trajectory
    - tike.view

about:
  home: https://github.com/AdvancedPhotonSource/tike
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: |
    Tike is a toolbox for tomographic reconstruction of 3D objects from
    ptychography data.
  description: |
    The aim of Tike is to provide fast and accurate implementations of a wide
    variety of reconstruction algorithms, and to provide a common platform for
    the synchrotron research community.
  doc_url: https://tike.readthedocs.io/
  dev_url: https://github.com/AdvancedPhotonSource/tike

extra:
  recipe-maintainers:
    - carterbox
